# Generated by Django 4.2.2 on 2024-02-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdbm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='qr_image'),
        ),
    ]
