# Generated by Django 4.2.2 on 2024-02-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdbm', '0002_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='qr_images'),
        ),
    ]
