# Generated by Django 4.2.2 on 2024-02-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdbm', '0003_alter_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
