# Generated by Django 4.2.2 on 2024-02-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdbm', '0004_remove_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
